spring.application.name=student-wallet-ai
spring.datasource.url=jdbc:postgresql://localhost:5432/studentwallet
spring.datasource.username=postgres
spring.datasource.password=samhit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true